[Addon]
Name=fcitx-table
GeneralName=Table
GeneralName[ca]=Taula
GeneralName[da]=Tabel
GeneralName[de]=Tabelle
GeneralName[es]=Tabla
GeneralName[fr]=Tableau
GeneralName[ja]=Table
GeneralName[ko]=표
GeneralName[ru]=Таблица
GeneralName[zh_CN]=码表
GeneralName[zh_TW]=碼表
Comment=Table Input Method for Fcitx
Comment[ca]=Mètode d'entrada de taula per a fcitx
Comment[da]=Tabel-inputmetode til Fcitx
Comment[de]=Table Eingabemethode für Fcitx
Comment[fr]=Méthode de saisie de table pour Fcitx
Comment[ja]=Fcitx 用のテーブル入力メソッド
Comment[ko]=Fcitx용 표 입력기
Comment[ru]=Метод ввода таблиц для Fcitx
Comment[zh_CN]=Fcitx 的码表输入法
Comment[zh_TW]=Fcitx 的碼表輸入法
Category=InputMethod
Enabled=True
Library=fcitx-table.so
Type=SharedLibrary
Dependency=fcitx-punc
SubConfig=Table:configfile:table/*.conf:table.desc,fcitx:domain
IMRegisterMethod=Self
