[Addon]
Name=fcitx-sunpinyin
GeneralName=Sunpinyin
GeneralName[ca]=Sunpinyin
GeneralName[da]=Sunpinyin
GeneralName[de]=Sunpinyin
GeneralName[ja]=Sunpinyin
GeneralName[ko]=Sunpinyin
GeneralName[ru]=Sunpinyin
GeneralName[tr]=Sunpinyin
GeneralName[zh_CN]=Sunpinyin
GeneralName[zh_TW]=Sunpinyin
Comment=Sunpinyin Wrapper For Fcitx
Comment[ca]=Contenidor sunpinyin per a fcitx
Comment[da]=Sunpinyin-wrapper til Fcitx
Comment[de]=Sunpinyin Wrapper für Fcitx
Comment[ja]=Fcitx 用 Sunpinyin ラッパー
Comment[ko]=Fcitx용 Sunpinyin 래퍼
Comment[ru]=Обертка LibPinyin для Fcitx
Comment[tr]=Fcitx için Sunpinyin Wrapper
Comment[zh_CN]=Fcitx 的 Sunpinyin 封装
Comment[zh_TW]=Fcitx 的 Sunpinyin 封装
Category=InputMethod
Enabled=True
Library=fcitx-sunpinyin.so
Type=SharedLibrary
Dependency=
IMRegisterMethod=ConfigFile
